export const AppInsightsEventMapping: Record<string, string> = {
    "LCWChatButtonClicked": "LCWChatButtonActionStarted",
    "WidgetLoadStarted": "WidgetStartChatStarted",
    "WidgetLoadComplete": "WidgetStartChatCompleted",
    "WidgetLoadFailed": "WidgetStartChatFailed",
    "PrechatSubmitted": "PrechatSubmitCompleted",
    "StartChatEventRecevied": "StartChatEventReceivedCompleted",
    "EndChatEventReceived": "EndChatEventReceivedCompleted",
    "EmailTranscriptSent": "EmailTranscriptActionCompleted",
    "EmailTranscriptFailed": "EmailTranscriptActionFailed",
    "HeaderCloseButtonClicked": "CloseChatActionStarted",
    "HeaderMinimizeButtonClicked": "MinimizeChatActionStarted",
    "DownloadTranscriptButtonClicked": "DownloadTranscriptActionStarted",
    "EmailTranscriptButtonClicked": "EmailTranscriptButtonActionStarted",
    "CustomerVoiceFormResponseSubmitted": "CustomerVoiceFormResponseSubmitCompleted",
    "StartProactiveChatEventReceived": "StartProactiveChatEventReceivedCompleted",
    "ProactiveChatRejected": "ProactiveChatTimeOutCompleted",
    "MessageSent": "MessageSentCompleted",
    "MessageReceived": "MessageReceivedCompleted",
    "SystemMessageReceived": "SystemMessageReceivedCompleted",
    "RehydrateMessageReceived": "RehydrateMessageReceivedCompleted",
    "CustomContextReceived": "CustomContextReceivedCompleted",
    "PostChatContextCallSucceed": "PostChatContextCallCompleted",
};