export const AppInsightsEventMapping: Record<string, string> = {
    "LCWChatButtonClicked": "LCWChatButtonActionStarted",
    "PrechatSubmitted": "PrechatSubmitCompleted",
    "StartChatEventRecevied": "StartChatEventReceivedCompleted",
    "EndChatEventReceived": "EndChatEventReceivedCompleted",
    "EmailTranscriptSent": "EmailTranscriptActionCompleted",
    "EmailTranscriptFailed": "EmailTranscriptActionFailed",
    "HeaderCloseButtonClicked": "CloseChatActionStarted",
    "HeaderMinimizeButtonClicked": "MinimizeChatActionStarted",
    "DownloadTranscriptButtonClicked": "DownloadTranscriptActionStarted",
    "EmailTranscriptButtonClicked": "EmailTranscriptButtonActionStarted",
    "CustomerVoiceFormResponseSubmitted": "CustomerVoiceFormResponseSubmitCompleted",
    "StartProactiveChatEventReceived": "StartProactiveChatEventReceivedCompleted",
    "ProactiveChatRejected": "ProactiveChatTimeOutCompleted",
    "MessageSent": "MessageSentCompleted",
    "MessageReceived": "MessageReceivedCompleted",
    "SystemMessageReceived": "SystemMessageReceivedCompleted",
    "RehydrateMessageReceived": "ChatHistoryMessageReceivedCompleted",
    "CustomContextReceived": "CustomContextReceivedCompleted",
    "NewTokenValidationStarted": "AuthTokenValidationStarted",
    "NewTokenValidationCompleted": "AuthTokenValidationCompleted",
    "NewTokenValidationFailed": "AuthTokenValidationFailed",
};