enum ChatWidgetEvents {
    ADD_ACTIVITY = "CHAT_WIDGET/ADD_ACTIVITY",
    FETCH_PERSISTENT_CHAT_HISTORY = "CHAT_WIDGET/FETCH_PERSISTENT_CHAT_HISTORY",
    NO_MORE_HISTORY_AVAILABLE = "CHAT_WIDGET/NO_MORE_HISTORY_AVAILABLE",
    HISTORY_LOAD_ERROR = "CHAT_WIDGET/HISTORY_LOAD_ERROR",
    HISTORY_BATCH_LOADED = "CHAT_WIDGET/HISTORY_BATCH_LOADED"
}

export default ChatWidgetEvents;