enum ChatWidgetEvents {
    ADD_ACTIVITY = "CHAT_WIDGET/ADD_ACTIVITY",
    FETCH_PERSISTENT_CHAT_HISTORY = "CHAT_WIDGET/FETCH_PERSISTENT_CHAT_HISTORY",
    NO_MORE_HISTORY_AVAILABLE = "CHAT_WIDGET/NO_MORE_HISTORY_AVAILABLE",
    HIDE_LOADING_BANNER = "CHAT_WIDGET/HIDE_LOADING_BANNER",
    HISTORY_LOAD_ERROR = "CHAT_WIDGET/HISTORY_LOAD_ERROR"
}

export default ChatWidgetEvents;