name: chat-components-pr

on:
  pull_request:
    branches:
      - '**'
    types: [ edited, assigned, opened, synchronize, reopened]
    paths:
      - 'chat-components/**'
      - '.github/workflows/**'
      
jobs: 
  build:
    runs-on: windows-2022
    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.X
      - name: Install packages
        working-directory: chat-components
        run: yarn install
      - name: Unit Tests
        working-directory: chat-components
        run: yarn test:unit
      - name: Build Storybook
        working-directory: chat-components
        env :
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build-storybook
      - name: VRT Tests
        working-directory: chat-components
        run: yarn test:visual --forceExit
      - name: Upload VRT Tests failures screenshots
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: VRT Failure Screenshots
          path: 'chat-components/**/__diff_output__/*.png'
      - name: Build package
        working-directory: chat-components
        run: yarn build
