name: storybook-release
on: 
  push:
    branches: 
      - main
    tags:
      - 'w-v*'
    paths:
      - 'chat-widget/**'

permissions:
  actions: write
  contents: write
  deployments: write
  packages: write

jobs:
  build-and-deploy:
    if: github.repository == 'microsoft/omnichannel-chat-widget'
    runs-on: ubuntu-latest
    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
      - name: Install Chat Widget packages
        working-directory: chat-widget
        run: yarn install
      - name: Build Composite Storybook
        working-directory: chat-widget
        env :
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build-composite-storybook
      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc # v4.3.3
        with:
          branch: gh-pages
          folder: ./chat-widget/storybook-build
          target-folder: docs/storybook
